// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { relations } from "drizzle-orm/relations";
import { appUsers, infractions, infractionResponseAudit } from "./db_schema";

export const infractionsRelations = relations(infractions, ({one, many}) => ({
	appUser_issuerId: one(appUsers, {
		fields: [infractions.issuerId],
		references: [appUsers.id],
		relationName: "infractions_issuerId_appUsers_id"
	}),
	appUser_studentId: one(appUsers, {
		fields: [infractions.studentId],
		references: [appUsers.id],
		relationName: "infractions_studentId_appUsers_id"
	}),
	infractionResponseAudits: many(infractionResponseAudit),
}));

export const appUsersRelations = relations(appUsers, ({many}) => ({
	infractions_issuerId: many(infractions, {
		relationName: "infractions_issuerId_appUsers_id"
	}),
	infractions_studentId: many(infractions, {
		relationName: "infractions_studentId_appUsers_id"
	}),
	infractionResponseAudits: many(infractionResponseAudit),
}));

export const infractionResponseAuditRelations = relations(infractionResponseAudit, ({one}) => ({
	appUser: one(appUsers, {
		fields: [infractionResponseAudit.studentId],
		references: [appUsers.id]
	}),
	infraction: one(infractions, {
		fields: [infractionResponseAudit.infractionId],
		references: [infractions.id]
	}),
}));