-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE app_users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL,
  section TEXT,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE code_logbook (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  filename TEXT NOT NULL,
  purpose TEXT NOT NULL,
  feature TEXT NOT NULL,
  date_added TEXT NOT NULL
);

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE infraction_response_audit (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  infraction_id INTEGER NOT NULL,
  student_id TEXT NOT NULL,
  response_text TEXT NOT NULL,
  submitted_at INTEGER DEFAULT (unixepoch()),
  FOREIGN KEY (infraction_id) REFERENCES infractions(id),
  FOREIGN KEY (student_id) REFERENCES app_users(id)
);

CREATE TABLE infractions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  student_id TEXT NOT NULL,
  issuer_id TEXT NOT NULL,
  type TEXT NOT NULL,
  offense TEXT NOT NULL,
  points INTEGER NOT NULL,
  description TEXT,
  date_issued INTEGER DEFAULT (unixepoch()), student_response TEXT, response_submitted_at INTEGER, resolved INTEGER DEFAULT 0, resolved_by TEXT, resolved_at INTEGER, student_explanation TEXT, explanation_submitted_at INTEGER,
  FOREIGN KEY (student_id) REFERENCES app_users(id),
  FOREIGN KEY (issuer_id) REFERENCES app_users(id)
);

CREATE TABLE invite_codes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL,
  section TEXT,
  max_uses INTEGER NOT NULL DEFAULT 1,
  used_count INTEGER NOT NULL DEFAULT 0,
  expires_at INTEGER NOT NULL,
  created_by TEXT NOT NULL,
  created_at INTEGER DEFAULT (unixepoch())
);

-- INDEXS

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX idx_app_users_name ON app_users(full_name);

CREATE INDEX idx_app_users_role ON app_users(role);

CREATE INDEX idx_app_users_section ON app_users(section);

CREATE INDEX idx_infractions_date ON infractions(date_issued);

CREATE INDEX idx_infractions_student ON infractions(student_id);
