// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, index, foreignKey } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const appUsers = sqliteTable("app_users", {
	id: text().primaryKey(),
	email: text().notNull(),
	fullName: text("full_name").notNull(),
	role: text().notNull(),
	section: text(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("idx_app_users_name").on(table.fullName),
	index("idx_app_users_section").on(table.section),
	index("idx_app_users_role").on(table.role),
]);

export const inviteCodes = sqliteTable("invite_codes", {
	id: integer().primaryKey({ autoIncrement: true }),
	code: text().notNull(),
	role: text().notNull(),
	section: text(),
	maxUses: integer("max_uses").default(1).notNull(),
	usedCount: integer("used_count").default(0).notNull(),
	expiresAt: integer("expires_at").notNull(),
	createdBy: text("created_by").notNull(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
});

export const infractions = sqliteTable("infractions", {
	id: integer().primaryKey({ autoIncrement: true }),
	studentId: text("student_id").notNull().references(() => appUsers.id),
	issuerId: text("issuer_id").notNull().references(() => appUsers.id),
	type: text().notNull(),
	offense: text().notNull(),
	points: integer().notNull(),
	description: text(),
	dateIssued: integer("date_issued").default(sql`(unixepoch())`),
	studentResponse: text("student_response"),
	responseSubmittedAt: integer("response_submitted_at"),
	resolved: integer().default(0),
	resolvedBy: text("resolved_by"),
	resolvedAt: integer("resolved_at"),
	studentExplanation: text("student_explanation"),
	explanationSubmittedAt: integer("explanation_submitted_at"),
},
(table) => [
	index("idx_infractions_date").on(table.dateIssued),
	index("idx_infractions_student").on(table.studentId),
]);

export const codeLogbook = sqliteTable("code_logbook", {
	id: integer().primaryKey({ autoIncrement: true }),
	filename: text().notNull(),
	purpose: text().notNull(),
	feature: text().notNull(),
	dateAdded: text("date_added").notNull(),
});

export const infractionResponseAudit = sqliteTable("infraction_response_audit", {
	id: integer().primaryKey({ autoIncrement: true }),
	infractionId: integer("infraction_id").notNull().references(() => infractions.id),
	studentId: text("student_id").notNull().references(() => appUsers.id),
	responseText: text("response_text").notNull(),
	submittedAt: integer("submitted_at").default(sql`(unixepoch())`),
});

